name: Test

on:
  workflow_call:
    inputs:
      runs-on:
        description: "OS to run the workflow on."
        required: true
        type: string

      test-type:
        description: "Type of test."
        required: true
        type: string

      shell:
        description: "Shell to use."
        required: true
        type: string

      device:
        description: "Device to use."
        required: true
        type: string

      pool:
        description: "Pool used to run the jobs."
        required: false
        type: string

env:
  HF_HOME: ${{ github.workspace }}/.cache/huggingface

jobs:
  test:
    runs-on: ${{ inputs.runs-on }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run Setup
      uses: ./.github/actions/setup
      with:
        shell: ${{ inputs.shell }}
        hf_cache_key: ${{ github.workflow }}-${{ inputs.test-type }}-hf-cache
        requirements_file: test/requirements-test-${{ inputs.device }}.txt

    - name: Run Tests
      env:
        PYTEST_BASETEMP: ${{ github.workspace }}/.pytest_basetemp
      run: |
        coverage run --source=${{ github.workspace }}/olive -m pytest -v -s --log-cli-level=WARNING --junitxml=${{ github.workspace }}/logs/test-TestOlive.xml ${{ github.workspace }}/test/${{ inputs.test-type }} --basetemp ${{ env.PYTEST_BASETEMP }}
        coverage xml




  