name: UnitTests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - rel-*
    paths:
      - '**'
      - '!docs/*'
      - '!examples/README.md'
      - '!examples/**/README.md'
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!LICENSE'
      # commonly updated examples with no test
      - '!examples/deepseek/**'
      - '!examples/directml/llm/**'
      - '!examples/directml/stable_diffusion_xl/**'
      - '!examples/llama2/**'
      - '!examples/llama3/**'
      - '!examples/mistral/**'
      - '!examples/open_llama/**'
      - '!examples/phi2/**'
      - '!examples/phi3/**'
      - '!examples/phi3_5/**'
      - '!examples/qwen2_5/**'
  pull_request:
    paths:
      - '**'
      - '!docs/*'
      - '!examples/README.md'
      - '!examples/**/README.md'
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!LICENSE'
      # commonly updated examples with no test
      - '!examples/deepseek/**'
      - '!examples/directml/llm/**'
      - '!examples/directml/stable_diffusion_xl/**'
      - '!examples/llama2/**'
      - '!examples/llama3/**'
      - '!examples/mistral/**'
      - '!examples/open_llama/**'
      - '!examples/phi2/**'
      - '!examples/phi3/**'
      - '!examples/phi3_5/**'
      - '!examples/qwen2_5/**'

env:
  HF_HOME: ${{ github.workspace }}/.cache/huggingface
  HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
  WORKSPACE_SUBSCRIPTION_ID: ${{ secrets.WORKSPACE_SUBSCRIPTION_ID }}
  WORKSPACE_RESOURCE_GROUP: ${{ secrets.WORKSPACE_RESOURCE_GROUP }}
  WORKSPACE_NAME: ${{ secrets.WORKSPACE_NAME }}
  MANAGED_IDENTITY_CLIENT_ID: ${{ secrets.MANAGED_IDENTITY_CLIENT_ID }}
  EXCLUDE_MANAGED_IDENTITY_CREDENTIAL: ${{ secrets.EXCLUDE_MANAGED_IDENTITY_CREDENTIAL }}  

jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: "ubuntu-latest", device: "cpu", shell: "bash"}
        - { os: "windows-latest", device: "cpu", shell: "cmd" }

    name: Unit Tests | ${{ matrix.config.os }} | ${{ matrix.config.device }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - name: Debugging
      run: |
        echo "HF_HOME ${{ env.HF_HOME }}"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Setup
      uses: ./.github/actions/setup
      timeout-minutes: 30
      with:
        shell: ${{ matrix.config.shell }}
        hfcache_key: ${{ github.workflow }}-unittests-hfcache
        requirements_file: "test/requirements-test-${{ matrix.config.device }}.txt"

    - name: Run Tests
      env:
        PYTEST_BASETEMP: ${{ github.workspace }}/.pytest_basetemp
      run: |
        echo coverage run --source=${{ github.workspace }}/olive -m pytest -v -s --log-cli-level=WARNING --junitxml=${{ github.workspace }}/logs/test-TestOlive.xml ${{ github.workspace }}/test/unit_test --basetemp ${{ env.PYTEST_BASETEMP }}
        coverage run --source=${{ github.workspace }}/olive -m pytest -v -s --log-cli-level=WARNING --junitxml=${{ github.workspace }}/logs/test-TestOlive.xml ${{ github.workspace }}/test/unit_test --basetemp ${{ env.PYTEST_BASETEMP }}
        coverage xml
